# Generated by Django 5.2 on 2025-04-09 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatgroup'),
        ),
    ]
